### ISSUE TITLE
Holidays

### ISSUE THREAD

**Issue by earthboundkid** [tBaxter/questions-for-employers#1]
Holidays are not the same as vacations. I have been unpleasantly surprised several times to learn that a company does not follow federal/state holidays. For parents, this can especially be a pain, as schools typically do, so you may have to use a vacation day for your child's holiday.

**Comment by tBaxter** [comment]
Thanks! Is this referencing a specific question, or something to add? I'm thinking the latter, but want to double-check.

**Comment by earthboundkid** [comment]
https://github.com/tBaxter/questions-for-employers/commit/026225a4fdb1133b340a6f290e3c25914adc5cd2 fixes it. Thanks!
